# Generated by Django 4.1.4 on 2022-12-29 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literary', '0002_alter_textesource_essay_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literarysource',
            name='author',
            field=models.TextField(max_length=100, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='literarysource',
            name='title',
            field=models.TextField(max_length=100, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='literarysource',
            name='url_q',
            field=models.URLField(max_length=100, verbose_name='url'),
        ),
    ]
